### ISSUE TITLE
[prom-api] OKD vs OCP4

### ISSUE THREAD

**Issue by durandom** [AICoE/learn-katacoda#2]
Why is the scenario running on OKD 3.11 and not OCP4?

**Comment by 4n4nd** [comment]
the OCP4.2 init env time was considerably longer than OKd3.11

**Comment by 4n4nd** [comment]
New image for OCP4.3 should be available soon, we can test that for better performance

**Comment by 4n4nd** [comment]
https://github.com/openshift-labs/learn-katacoda/commit/811f4878c7afdff8617d30e09c63c90046f30f45
