### ISSUE TITLE
[prom-api]  console and notebook in iframes

### ISSUE THREAD

**Issue by durandom** [AICoE/learn-katacoda#3]
can we have the notebook and the OCP console as a tab/link in the same window?

**Comment by 4n4nd** [comment]
I tried to do it but the iframe forces https. So the user would have to open url in a new tab and accept the invalid certs first. ![Screenshot from 2020-03-05 21-43-45](https://user-images.githubusercontent.com/22333506/76028511-aa617400-5f2a-11ea-9b9b-78adbac9ae2c.png)

**Comment by 4n4nd** [comment]
@durandom ^ any suggestions for this?

**Comment by durandom** [comment]
Do the other scenarios on learn.openshift.com have https for their tabs? E.g. the openshift console? And how if so, what's the CA of their certificate?

**Comment by 4n4nd** [comment]
looking into it :+1:
