### ISSUE TITLE
[prom-api] pre-build the image

### ISSUE THREAD

**Issue by durandom** [AICoE/learn-katacoda#4]
To speed up startup time, can we pre-build the image?

<img width="612" alt="Screenshot 2020-03-03 at 07 58 09" src="https://user-images.githubusercontent.com/161888/75974930-ec14ff00-5ed7-11ea-956c-4ea890683ad7.png">

**Comment by 4n4nd** [comment]
I think I can pre-build the s2i image for the jupyter env.

**Comment by goern** [comment]
@CermakM @harshad16
