### ISSUE TITLE
ODH base image

### ISSUE THREAD

**Issue by durandom** [AICoE/learn-katacoda#6]
can we have an image with ODH images already in the registry

**Comment by goern** [comment]
@CermakM FYA

**Comment by 4n4nd** [comment]
https://github.com/openshift-labs/learn-katacoda/blob/master/environments/openshift-4-3/master/build/5_odh-pull.sh
We can add all the images needed by the odh-operator in this script so they are pre-pulled

**Comment by 4n4nd** [comment]
https://github.com/openshift-labs/learn-katacoda/pull/687
