### ISSUE TITLE
How to use thamos advise cleverness in your s2i Build process

### ISSUE THREAD

**Issue by goern** [AICoE/learn-katacoda#8]

**Comment by goern** [comment]
current state is shown in thoth sprint demo, see notes at  https://docs.google.com/document/d/1lyllLj3fDz_4WWolrDFimIN8Zwk_zxvGxhornn_KQXM/edit#heading=h.o7j38tzdjge2

**Comment by saisankargochhayat** [comment]
Demo - https://www.katacoda.com/saisankargochhayat/scenarios/hello-world
